const db = require('./db');

const collaborateursSchema = db.mongoose.Schema({
    prenom: String,
    nom: String,
    genre: String,
    dateDeNaissance: String,
    villeDeNaissance: String,
    nomDeNaissance: String,
    nationalite: String,
    numerosecurite: String,
    addresse: String,
    cp: String,
    ville: String,
    email: String,
    telephonePerso: String,
    telephoneDomicile: String,
    telephoneUrgence: String,
    rpps: String,
    numeroDepartemental: String,
    departementConseil: String,
    specialitePratiquee: String,
    matériels: String,
    contrat: String,
    déclaration: String,
    fichedeposte: String,
    fichesynthetique: String,
    avantagesennature: String,
    mutuelle: String,
    onboarding: String,
    fonctiondigitalsecondaire: String,
    datedeprisedefonction: String,
    telephonetravail: String,
    telephonemobile: String,
    adressetravail: String,
    activite: String,
    emailresponsable: String,
    etablissement: String,
    fonctiondigital: String,
    juridique: String,
    collaborteur: String,
    convention: String,
    erp: String,
    naturetravail: String,
    tempstravail: String,
    classification: String,
    niveau: String,
    indice: String,
    rémunérationbrutemensuelle: String,
    rémunérationbrutejournalière: String,
    rémunérationbruteannuelle: String,
    rémunérationbrutehoraire: String,
    nombreheureshebdomadairedusalarie: String,
    nombreheuresmensueldusalarié: String,
});


const collaborateursModel = db.mongoose.model('collaborateurs', collaborateursSchema);

module.exports = collaborateursModel;